[package]
name = "team5"
version = "0.1.0"
edition = "2024"

[dependencies]
rkyv = { version = "0.7", default-features = true, features = ["std", "alloc", "validation"] }
#fd-lock = "*"
fs2 = "*"
single-instance = "*"
bytecheck = "0.6"
bytemuck = "*"

aes-gcm = { version = "*", features = ["zeroize"] }
argon2 = "*"
rand = "0.8"
rand_chacha = "0.3"
sysinfo = "0.30"
rsa = "0.9"
sha2 = "0.10"
zeroize = { version = "*", features = ["derive"] }
memlock = "*"

url = "*"
eframe = "0.33.3"
log = "0.4.29"
