[package]
name = "team5"
version = "0.1.0"
edition = "2024"

[dependencies]
rkyv = { version = "0.7", default-features = true, features = ["std", "alloc", "validation"] }
bytecheck = "0.6"
aes-gcm = { version = "*", features = ["zeroize"] }
argon2 = "*"
rand = "*"
zeroize = { version = "*", features = ["derive"] }
eframe = "0.33.3"
