[package]
name = "team5"
version = "0.1.0"
edition = "2024"

[dependencies]
rkyv = { version = "0.8"}
fs2 = "*"
single-instance = "*"
bytemuck = "*"

aes-gcm = { version = "*", features = ["zeroize"] }
argon2 = "*"
rand = "0.8"
sysinfo = "0.30"
ecies = "*"
sha2 = "0.10"
zeroize = { version = "*", features = ["derive"] }
memlock = "*"

eframe = "0.33.3"
log = "0.4.29"
url = "2.5.8"

[patch.crates-io]
# 라이브러리 A가 내부적으로 쓰는 library_b도 로컬 경로로 강제 지정
url = { path = "./libs/url-2.5.8" }
