[package]
name = "team5"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 2
debug = true
panic = "unwind"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "unwind"

[workspace]
members = ["engine", "cli", "ui"]

[dependencies]
memlock = "*"

cli = {path = "./cli"}
single-instance = "*"


[workspace.dependencies]
zeroize = { version = "*", features = ["derive"] }
arboard = "*"
single-instance = "*"


[features]

