[package]
name = "team5"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 2
debug = true
panic = "abort"

[workspace]
members = ["engine", "app", "cli", "ui"]

[dependencies]
memlock = "*"

cli = {path = "./cli"}
single-instance = "*"


[workspace.dependencies]
zeroize = { version = "*", features = ["derive"] }
single-instance = "*"


[features]

