[package]
name = "team5"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 3
debug = true
panic = "abort"

[workspace]
members = ["./core", "./app", "./cli", "./ui", "ui"]

[dependencies]
single-instance = "*"
memlock = "*"
eframe = { version = "0.33.3", optional = true }

[workspace.dependencies]
zeroize = { version = "*", features = ["derive"] }


[features]
gui = ["eframe"]
cui = []
