[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { path = "../app" }
engine = { path = "../engine" }
eframe = { version = "0.33.3" }
zeroize = { workspace = true }

[features]
gui = []
cui = []

